#!/bin/zsh

RG='rg --column --line-number --no-heading --fixed-strings --ignore-case --no-ignore --hidden --follow --color always \
  -g "*.{js,jsx,json,php,md,styl,jade,html,config,py,cpp,c,go,hs,rb,conf,ts,tsx}" \
  -g "!*{git,node_modules,vendor}/*" \
  -g "!*package-lock.json*"'

CMD="${RG} ${1}"

eval ${CMD}
